#!/bin/bash

CPUS="`cat /proc/cpuinfo  | grep processor | wc -l`"

# test avr tool chain
if avr-gcc -v > /dev/null 2>&1
then
  echo
  echo "BUILDING WITH AVR-GCC"
  for p in debug release test mtest profile doc
  do
    ( cd test_app_avr && make PROFILE="$p" TC="avr" "-j$CPUS" ) || exit $?
  done # for profile
else
  echo "WARNING: AVR toolchain not found - not testing..." >&2
fi

# test intel tool chain
if icc -v > /dev/null 2>&1
then
  echo
  echo "BUILDING WITH ICC"
  for p in debug release test mtest profile doc
  do
    ( cd test_app_intel && make PROFILE="$p" TC="intel" "-j$CPUS" ) || exit $?
  done # for profile
else
  echo "WARNING: intel's toolchain not found - not testing..." >&2
fi

# test gcc tool chain
if gcc -v > /dev/null 2>&1
then
  echo
  echo "BUILDING WITH GCC"
  for p in debug release test mtest profile doc
  do
    ( cd test_app && make PROFILE="$p" TC="gcc" "-j$CPUS" ) || exit $?
  done # for profile
else
  echo "WARNING: gcc toolchain not found - not testing..." >&2
fi

# test clang tool chain
if clang -v > /dev/null 2>&1
then
  echo
  echo "BUILDING WITH CLANG"
  for p in debug release test mtest doc
  do
    ( cd test_app && make PROFILE="$p" TC="clang" "-j$CPUS" ) || exit $?
  done # for profile
else
  echo "WARNING: clang toolchain not found - not testing..." >&2
fi

# test mem-debug feature of main build process
echo
echo "BUILDING IN MEM_DEBUG MODE"
( cd test_app && make PROFILE="test" MEM_DEBUG=1 "-j$CPUS" ) || exit $?

# test building few features for test_app
echo
echo "BUILDING DIFFERENT FEATURE SETS"
( cd test_app && make PROFILE="test" FEATURES="ans1 ft1" "-j$CPUS" ) || exit $?
( cd test_app && make PROFILE="test" FEATURES="ans1 ft2" "-j$CPUS" ) || exit $?
( cd test_app && make PROFILE="test" FEATURES="ans2 ft1" "-j$CPUS" ) || exit $?
( cd test_app && make PROFILE="test" FEATURES="ans2 ft2" "-j$CPUS" ) || exit $?
# this is negative test - feature 'ft3' should NOT compile!
( cd test_app && make PROFILE="test" FEATURES="ans1 ft3" "-j$CPUS" 2>/dev/null ) && exit 1

# test small-projects build process
for t in debug release profile test
do
  echo
  echo "BUILDING WITH SMALL PROJECTS BUILD PROCESS: $t"
  echo "test_app:"
  ( cd small_prj_build_process/test_app  && make "$t" "-j$CPUS" ) || exit $?
  for tc in gcc avr
  do
    [ "$tc" = "avr" ] && [ "$t" = "test" ] && continue
    echo "test_app2:"
    ( cd small_prj_build_process/test_app2 && make "TC=$tc" "$t" "-j$CPUS" ) || exit $?
  done
done # for targets
