#ifndef INCLUDE_BUILD_PROCESS_FORCELINK_HPP_FILE
#define INCLUDE_BUILD_PROCESS_FORCELINK_HPP_FILE

#define FORCE_LINK_THIS_OBJECT(name) extern const bool FORCE_LINK_THIS_OBJECT__##name##__END=true;

#endif
